server:
  port: 9001
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      server-addr: 192.168.1.188:8848
    gateway:
      routes: # 网关路由配置
        - id: user-server # 路由id 自定义 唯一即可
          uri: lb://user-server # 路由目标地址
          predicates: #路由断言,判断前缀是user的才路由到user-server
            - Path=/user/**
    #      filters: # 给为user-server的请求 添加过滤器
     #       - AddRequestHeader=name,dongwei #在请求头里添加一个为name 为dongwei参数
      default-filters:
        - AddRequestHeader=origin,gateway #配置全局的过滤器
      globalcors: #全局跨域处理
        add-to-simple-url-handler-mapping: true #解决options请求拦截问题
        cors-configurations: # 允许那些网站跨域请求
          '[/**]':
            allowedOrigins: #允许的ajax 的请求方式
              - "http://localhost:8090"
              - "https:www.baidu.com"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 36000 #这次跨域检测的有效期
