server:
  port: 8091
spring:
  application:
    name: consumer
  cloud:
    nacos:
      server-addr: 124.223.2.193:8848
      # 添加集群
      discovery:
        cluster-name: HZ
        # 添加命名空间
#        namespace: 46587682-2495-474d-b896-91b6a022dc6b
        #配置是否是临时实例
      #  ephemeral: false
    sentinel:
      transport:
        dashboard: 124.223.2.193:8858
  rabbitmq:
    host: 124.223.2.193
    port: 5672
    virtual-host: /
    username: admin
    password: admin
  #eureka:
  #  client:
  #    service-url:
  #      defaultZone: http://127.0.0.1:8080/eureka
  # 给user-server配置 ribbon 负载
user-server:
  ribbon:
    # 配置负载均衡的规则
   # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 配置为Nacos的负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: user-server #指定接加载的服务名称
#        如果有多个
#      - user-server
#      -

